name: Actualizar Noticias Ganaderia

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Esto asegura permisos de escritura desde el código
      contents: write
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Trae todo el historial para evitar conflictos

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar el scraper
        run: python scraper.py

      - name: Guardar cambios en el JSON
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add noticias.json
          # El comando 'pull --rebase' mezcla tus cambios web con los del bot sin errores
          git pull --rebase origin main
          git commit -m "Actualización automática de noticias" || echo "No hay cambios para subir"
          git push origin main
